# Generated by Django 5.0.2 on 2024-02-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land_service', '0002_landservice_lawyerservice_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerservice',
            name='service_provider',
        ),
    ]
