# Generated by Django 5.0.2 on 2024-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='color',
            field=models.IntegerField(default=1),
        ),
    ]
