# Generated by Django 5.0.2 on 2024-04-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
