# Generated by Django 5.0.2 on 2024-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_land_location_alter_land_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
